name: Manhunt
version: ${project.version}
main: org.github.brokenearthdev.manhunt.ManhuntPlugin
api-version: 1.16

commands:
  mhstart:
    usage: /<command>
    description: starts the game
  mhstop:
    usage: /<command>
    description: stops the game
  mhprofile:
    usage: /<comand>
    description: access the profile
  mhtracker:
    usage: /<command>
    description: gives a tracker to the hunter if, for some reason, the hunter doesn't have a compass
  mhtp:
    usage: /<command>
    description: teleports players to a world with the specified type

permissions:
  manhunt.game.options:
    description: Allows players to access and customize game settings
    default: op
  manhunt.game.start:
    description: Allows players to access the /mhstart command
    default: op
  manhunt.game.stop:
    description: Allows players to access the /mhstop command
    default: op
  manhunt.game.worldtp:
    description: Allows players to access the /mhworld command
    default: op
  manhunt.profile:
    description: Allows players to access the /mhprofile command
    default: true